### ISSUE TITLE
Demos?

### ISSUE THREAD

**Issue by coler-j** [johnfraney/django-bootstrap-customizer#1]
### Description

Is there any demos of what this will look like?

**Comment by johnfraney** [comment]
@coler-j I was thinking that I needed to add that. There is an example project included in the repo (which I need to document).

Here's a screenshot of the `BootstrapTheme` admin page:

![screen shot 2018-09-10 at 12 02 01-fullpage](https://user-images.githubusercontent.com/1728528/45305778-718d3e00-b4f1-11e8-97f7-d4334d035727.png)

And here's the example app with a customized theme:

![screen shot 2018-09-10 at 12 01 34-fullpage](https://user-images.githubusercontent.com/1728528/45305796-7d790000-b4f1-11e8-8c96-8a48ac5d58da.png)

**Comment by coler-j** [comment]
Yeah that is nice. Good work!
