### ISSUE TITLE
Error creating a BootstrapTheme  from Django Admin

### ISSUE THREAD

**Issue by matteodarecchio** [johnfraney/django-bootstrap-customizer#2]
* Package version: lastest
* Django version: 2.1
* Python version: 3.7
* Operating System: Windows 10

Hi, I am following the quick start on https://johnfraney.github.io/django-bootstrap-customizer/#quickstart, but when I try to create a BootstrapTheme  from Django Admin I get this error on the admin: Error: 
File to import not found or unreadable: C:UsersmatteodarecchioWEB jango2venvlibsite-packagesootstrap_customizerstaticootstrapscssootstrap.scss. on line 25 of stdin >> @import "C:\Users\matteodarecchio\WEB\django2venv\lib\site-packages\bootstra ^ 

Installing Django Bootstrap Customizer, the path of bootstrap.scss file is 
C:\Users\matteodarecchio\WEB\django2venv\Lib\site-packages\bootstrap_customizer\static\bootstrap\scss

Have I to move bootstrap.scss file to another path?

Thanks

**Comment by johnfraney** [comment]
@matteodarecchio Hmm! I haven't tested this library on a Windows machine. I'll see if I can get a Windows development environment set up this evening to reproduce this.

**Comment by matteodarecchio** [comment]
Ok Thanks, I can try also with Mac Os X. I am going to do that in these days.

**Comment by alexandra-picot** [comment]
Hello, I tried this library on Mac OS Mojave and it worked perfectly, but then I tried on Windows 10 and get the same problem. Did you find a solution ?

**Comment by matteodarecchio** [comment]
Hello, thanks! No sorry, I didn't find a solution yet.

**Comment by johnfraney** [comment]
@matteodarecchio Thanks to @vincent-picot , this should be solved in the latest release, [v0.1.4](https://github.com/johnfraney/django-bootstrap-customizer/releases/tag/v0.1.4).
